### ISSUE TITLE
Simulation based on model fit

### ISSUE THREAD

**Issue by MahmoudAliAfifi** [certara/R-Certara#2]
Hi,

I am making model fitting for 1000 bootstrap datasets, and after I reach to best fit, I want to simulate based on model fit object.

my question is: is there a function to make a simulation based on the final estimates of (modelfit function)?

for example:

x<- fitmodel(pkModel)
then
simmodel(x)

simmodel will take the model and its estimates from the best fitting.

**Comment by certara-jcraig** [comment]
Hi @MahmoudAliAfifi  -  discussions around this occurred via email and I apologize for the delay in closing this issue. Thank you again for the great presentation at Certara R School last month, where you demonstrated simulation-re-estimation approaches in RsNLME via a case study.  For those who are interested, the recording and files can be found here: https://certara.github.io/R-Certara/articles/lesson_9.html

As you now know from your usage of RsNLME, we can use the `copyModel()` function to create a new model with the final parameters estimates from the fitted model:

```
library(Certara.RsNLME)

# Create base model
model <- pkmodel(
  parameterization = "Clearance",
  numCompartments = 2,
  data = pkData,
  ID = "Subject",
  Time = "Act_Time",
  A1 = "Amount",
  CObs = "Conc"
)

#Fit base model using fitmodel()
fit_output <- fitmodel(model)

# Copy model using copyModel(), accepting final parameter estimates from model fit
model2 <- copyModel(model, acceptAllEffects = TRUE)

# Run simulation using simmodel()
sim_output <- simmodel(model2)
```

**Comment by MahmoudAliAfifi** [comment]
Thanks a lot James.
